[package]
name = "static_table_derive"
version = "0.1.28"
description = "Procedural macros for investments crate"

authors = ["Dmitry Konishchev <konishchev@gmail.com>"]
homepage = "https://github.com/KonishchevDmitry/investments"
license = "GPL-3.0+"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.13.0"
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = "1.0.73"
