[package]
name = "static_table_derive"
version = "0.1.2"
description = "Procedural macros for investments crate"

authors = ["Dmitry Konishchev <konishchev@gmail.com>"]
homepage = "https://github.com/KonishchevDmitry/investments"
license = "GPL-3.0+"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
darling = "0.10.2"
proc-macro2 = "1.0.13"
quote = "1.0.6"
syn = "1.0.22"
