[package]
name = "static_table_derive"
version = "0.1.0"
edition = "2018"
authors = ["Dmitry Konishchev <konishchev@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
darling = "0.10.2"
proc-macro2 = "1.0.7"
quote = "1.0.2"
syn = "1.0.13"
